### ISSUE TITLE
Modifications to contacts fail with error message "The contact you were trying to edit has changed" after the first modification

### ISSUE THREAD

**Issue by tralph3** [nextcloud/contacts#2912]
### Describe the bug

If I try to edit a contact's info, I can do so no problem for the first thing. Let's say I want to change the name, and the surname. I can change the name no problem, but then if I want to change the surname, it fails telling me that "The contact you were trying to edit has changed". I need to reload the page, and edit it again. This is really annoying. It's CONSISTENTLY always after the first edit. If I reload, I made the edit I wanted, and want to make another one, then again, it pops up.

I've never not had this bug, it has always happened since I've installed the app.

### Steps to reproduce

1. Go to a contact
2. Modify any of its contents
3. Try to modify something else
4. Error

### Expected behavior

I should be able to modify as much as I want without problems.

### Actual behavior

I can't do more than a single modification per page refresh.

### Contact version

4.2.0

### Operating system

Arch Linux

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

### Additional info

Here you can see the network logs for this error:
![image](https://user-images.githubusercontent.com/41462117/188351281-54ebb334-a9de-44c2-97bc-b00d18e86699.png)

I did two modifications. I added a single character into the address field, which is the 204 request, and then I deleted it, resulting in a 412 request and the error popping up.

**Comment by Daugl** [comment]
I have the same bug with the exact same behavior
Operating system: Debian
PHP engine version: 7.4.30
Web server: Nginx
Database: Postgres

Only on Firefox, Chromium does just fine.

**Comment by TheAkio** [comment]
I can also confirm this bug using Firefox.

Contacts: 5.0.1
Nextcloud: Docker Image "nextcloud:25-apache"
PHP engine version: 8.1.12
Database: Postgres 14
Browser: Firefox 105
OS: Raspberry PI OS 64-bit

**Comment by Praetorian1410** [comment]
Same issue, also on Firefox, same configuratuon as TheAkio save for the DB: mysql V10.9.4.

**Comment by st3iny** [comment]
Do you have the maps app installed? If yes, then it's most likely this bug: https://github.com/nextcloud/maps/issues/864.

Updating maps should fix the issue.

**Comment by tralph3** [comment]
I do have maps installed, but it's already at the latest version.

**Comment by Daugl** [comment]
I don't have maps installed. Just tested it with contacts 5.0.2 and Nextcloud 25.0.3, still persists.

**Comment by brtwrst** [comment]
I have the same problem
Nextcloud (26.0.1)
Contacts 5.2.0
