### ISSUE TITLE
When adding an ungrouped contact to a group, the contact disappears in the UI

### ISSUE THREAD

**Issue by Ma27** [nextcloud/contacts#4175]
### Steps to reproduce

Given a contact that is ungrouped.
When I
* Click on "Not grouped"
* Edit the contact and add it to an existing contact group "X"
Then
* the contact disappears from the UI
* Contacts only shows me "There are no contacts yet"
* When I click on the contact group "X", the contact isn't shown there.
* When I reload Nextcloud, the contact is under "Not grouped" again.

### Expected behavior

The contact must not disappear, I should have a chance to save the contact. The way it's currently done, unsaved data is thrown away.

### Actual behavior

See above under "Then".

### Contact version

6.1.0

### Operating system

NixOS 24.05

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database

PostgreSQL

**Comment by hamza221** [comment]
@Ma27 Can you please double check the app version. Because I thought this was fixed on version 6.1.0 and I couldn't reproduce

**Comment by Ma27** [comment]
@hamza221 not reproducible on 6.1.0 exactly?
Because my Nextcloud lists exactly that version as installed.

**Comment by Ma27** [comment]
@hamza221 Still an issue with 7.1.0 fwiw.

EDIT: checked on 7.1.3 again, with the same result.

**Comment by trainedmoose** [comment]
Unfortunately the issue is still present:

- Nextcloud Hub 10 (31.0.9)
- Contacts 7.3.2

_A workaround_ is to create another user that is not grouped, so the actual user you're editing isn't the last. This will prevent the page from showing the "There are no contacts yet" message.

**Comment by DerDreschner** [comment]
Hey there, thanks for creating that issue! I tried to reproduce it with contacts 8.3.1 and firefox, but I'm unable to do so. The contact is immediately visible when I click on the group I've assigned.

That's why I'll close the issue for now. If you're still affected, feel free to add a comment here with the browser you're using and the operating system that we can have a closer look. Thanks again!!

**Comment by march42** [comment]
Contacts APP v7.3.13 on NextCloud v31.0.13
I can reproduce @DerDreschner and sched some light, because I would consider this 'expected behaviour'.
After selecting 'Ungrouped' in the group list left, the displayed contacts are filtered and only contacts without group will be displayed. When I edit a contact without group and select a group and save, it disappears from the list because it is no longer 'ungrouped'.
The filter works just, as i would expect.
The contact will show, if i select the appropriate group or 'all contacts'.

**Comment by trainedmoose** [comment]
> Contacts APP v7.3.13 on NextCloud v31.0.13 I can reproduce [@DerDreschner](https://github.com/DerDreschner) and sched some light, because I would consider this 'expected behaviour'. After selecting 'Ungrouped' in the group list left, the displayed contacts are filtered and only contacts without group will be displayed. When I edit a contact without group and select a group and save, it disappears from the list because it is no longer 'ungrouped'. The filter works just, as i would expect. The contact will show, if i select the appropriate group or 'all contacts'.

@march42 To shed some light: When this issue was raised, after changing the ungrouped contact's group, the contact editing UI **immediately** disappeared **without any option to save the contact**. This is not happening anymore (just like you experienced it). So it is fixed but was really broken ;)
