### ISSUE TITLE
Continuous HTTP error 412 on PUT requests to the address book

### ISSUE THREAD

**Issue by CamZie** [nextcloud/contacts#434]
### Steps to reproduce
1. use Mac OS X 10.13 as the client for the Contacts app (AddressBook/1806)
2. Synchronise your Contacts with the Nextcloud contacts app

### Expected behaviour
No 412 HTTP error should appear and the load on the server should not go higher.

### Actual behaviour
Continuous HTTP 412 PUT response for an address book (see below "Web-server access log"), which causes a high load on the database and takes up more server resource than it should.

We also noticed the errors in the nextcloud.log (see below "Nextcloud log"), which appears every 30 seconds. We are not sure if this is related to the 412 PUT responses.

### Server configuration

**Operating system**: Debian 9.1 (stretch)

**Web server:** Nginx 1.10.3

**Database:** MySQL 5.8

**PHP version:** 7

**Nextcloud version:** 12.0.2

**Contacts version:** 2.0.1

**Updated from an older Nextcloud or fresh install:** Updated from Nextcloud version 12

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enable_avatars": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "log_authfailip": true,
        "loglevel": 2,
        "maintenance": false,
        "customclient_desktop": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "share_folder": "\/Shared",
        "overwritewebroot": "\/",
        "overwriteprotocol": "https",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto,30",
        "activity_expire_days": 14,
        "logtimezone": "Europe\/Zurich",
        "log_type": "errorlog",
        "skeletondirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***"
    }
}
```
**Are you using encryption:** yes

### Client configuration
**Operating system:** Mac OS X/10.13.1

**CardDAV-clients:** Apple contacts

#### Web server access log
```
***REMOVED SENSITIVE VALUE*** - ***REMOVED SENSITIVE VALUE*** [13/Nov/2017:10:36:30 +0100] "PUT /remote.php/carddav/addressbooks/***REMOVED SENSITIVE VALUE***/Contacts/a3ab6572-e87f-4796-9e5f-2fec6bc8876e.vcf HTTP/1.1" 412 332 "-" "Mac OS X/10.13.1 (17B48) AddressBook/1806"
***REMOVED SENSITIVE VALUE*** - ***REMOVED SENSITIVE VALUE*** [13/Nov/2017:10:36:30 +0100] "PUT /remote.php/carddav/addressbooks/***REMOVED SENSITIVE VALUE***/Contacts/aa162dfd-a56d-4184-8f73-9bca641965a9.vcf HTTP/1.1" 412 332 "-" "Mac OS X/10.13.1 (17B48) AddressBook/1806"
***REMOVED SENSITIVE VALUE*** - ***REMOVED SENSITIVE VALUE*** [13/Nov/2017:10:36:30 +0100] "PUT /remote.php/carddav/addressbooks/***REMOVED SENSITIVE VALUE***/Contacts/29c6c947-f1a7-42e4-a655-2ba42e30b999.vcf HTTP/1.1" 412 332 "-" "Mac OS X/10.13.1 (17B48) AddressBook/1806"

```

#### Nextcloud log (data/nextcloud.log)
```
2017/11/13 10:35:33 [error] 497#497: *2192260 FastCGI sent in stderr: "PHP message: [owncloud][carddav][4] Exception: {"Exception":"Sabre\\DAV\\Exception\\InvalidSyncToken","Message":"Invalid or unknown sync token","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Sync\/Plugin.php(65): Sabre\\DAV\\Sync\\Plugin->syncCollection('addressbooks\/st...', Object(Sabre\\DAV\\Xml\\Request\\SyncCollectionReport))\n#1 [internal function]: Sabre\\DAV\\Sync\\Plugin->Sabre\\DAV\\Sync\\{closure}('{DAV:}sync-coll...', Object(Sabre\\DAV\\Xml\\Request\\SyncCollectionReport), 'addressbooks\/st...')\n#2 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#3 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(718): Sabre\\Event\\EventEmitter->emit('report', Array)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func" while reading response header from upstream, client: ***REMOVED SENSITIVE VALUE***, server: ***REMOVED SENSITIVE VALUE***, request: "REPORT /remote.php/carddav/addressbooks/***REMOVED SENSITIVE VALUE***/Contacts/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "***REMOVED SENSITIVE VALUE***"
```

#### Browser log
```
nothing relevant
```

**Comment by thoschl** [comment]
Same behaviour here. I informed Apple about this. But I am not sure if the problem is in contacts on the serverside. Try to sync with an iOS client and you'll see that it works. I also tried an older Addressbook-Client in OS X 11.6 and it works too.

**Comment by skjnldsv** [comment]
Have you tried our nightlies?
We fixed a similar issue.

**Comment by thoschl** [comment]
I tried the nightly nextcloud_contacts_nightly_build_2017-11-14.tar.gz and the issue still exists.

**Comment by thoschl** [comment]
As said, I paste logs from my nextcloud 12.0.3 Server and OS X 10.11.6 addressbook client. It's behind a reverse proxy. As you can see there are no 412 errors.
```
127.0.0.1 - - [12/Nov/2017:17:38:24 +0000] "PUT /REMOVED FOR PRIVACY REASONS/c102a2c5-a22f-483f-815b-f2bb3e2c5f38.vcf HTTP/1.1" 401 569 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - - [12/Nov/2017:17:38:24 +0000] "PUT /REMOVED FOR PRIVACY REASONS/c102a2c5-a22f-483f-815b-f2bb3e2c5f38.vcf HTTP/1.1" 401 569 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:38:26 +0000] "PUT /REMOVED FOR PRIVACY REASONS/c102a2c5-a22f-483f-815b-f2bb3e2c5f38.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:38:26 +0000] "PUT /REMOVED FOR PRIVACY REASONS/c102a2c5-a22f-483f-815b-f2bb3e2c5f38.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - - [12/Nov/2017:17:38:26 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 401 569 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - - [12/Nov/2017:17:38:26 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 401 569 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:38:27 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 682 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:38:27 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 682 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:38:58 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/9c531713-dd79-4cc5-8e86-b8e31ca44ff1.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:38:58 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/9c531713-dd79-4cc5-8e86-b8e31ca44ff1.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:38:59 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:38:59 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:39:06 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/b9f9d9cd-d0cc-4f00-b72d-5c83a78b5cd9.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:39:06 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/b9f9d9cd-d0cc-4f00-b72d-5c83a78b5cd9.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:39:07 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:39:07 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:39:22 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/a9ccc99b-1070-458d-a97c-3ffc6316385c.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:39:22 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/a9ccc99b-1070-458d-a97c-3ffc6316385c.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:39:23 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:39:23 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:39:28 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/ff986260-c8bd-499b-99d9-066ed37a41f0.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:39:28 +0000] "DELETE /REMOVED FOR PRIVACY REASONS/ff986260-c8bd-499b-99d9-066ed37a41f0.vcf HTTP/1.1" 204 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
127.0.0.1 - USERNAME [12/Nov/2017:17:39:29 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.33.99 - USERNAME [12/Nov/2017:17:39:29 +0000] "REPORT /REMOVED FOR PRIVACY REASONS/ HTTP/1.1" 207 654 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
```
Same server but accessed by the new macOS 10.13.2 client:
```
127.0.0.1 - - [14/Nov/2017:09:33:37 +0000] "OPTIONS /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - - [14/Nov/2017:09:33:37 +0000] "OPTIONS /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:38 +0000] "OPTIONS /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 200 0 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:38 +0000] "OPTIONS /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 200 0 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:43 +0000] "PROPFIND /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 207 1576 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:43 +0000] "PROPFIND /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 207 1576 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - - [14/Nov/2017:09:33:43 +0000] "PROPFIND /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - - [14/Nov/2017:09:33:43 +0000] "PROPFIND /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:45 +0000] "PROPFIND /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 207 3468 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:45 +0000] "PROPFIND /REMOVED FOR SECURITY REASONS/ HTTP/1.1" 207 3475 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:48 +0000] "PUT /REMOVED FOR SECURITY REASONS/default/ef5928d4-9d53-4425-a9d1-157bbd9687d6.vcf HTTP/1.1" 412 332 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:48 +0000] "PUT /REMOVED FOR SECURITY REASONS/default/ef5928d4-9d53-4425-a9d1-157bbd9687d6.vcf HTTP/1.1" 412 332 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:48 +0000] "PUT /REMOVED FOR SECURITY REASONS/default/9a6e18b1-91af-4144-a28c-cf2dbc8774bc.vcf HTTP/1.1" 412 324 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:48 +0000] "PUT /REMOVED FOR SECURITY REASONS/default/9a6e18b1-91af-4144-a28c-cf2dbc8774bc.vcf HTTP/1.1" 412 324 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:48 +0000] "PUT /REMOVED FOR SECURITY REASONS/default/ce0199a2-358c-4710-a7af-876c7eb2869d.vcf HTTP/1.1" 412 309 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:48 +0000] "PUT /REMOVED FOR SECURITY REASONS/default/ce0199a2-358c-4710-a7af-876c7eb2869d.vcf HTTP/1.1" 412 309 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
127.0.0.1 - USERNAME [14/Nov/2017:09:33:50 +0000] "REPORT /REMOVED FOR SECURITY REASONS/default/ HTTP/1.1" 403 4508 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
195.35.73.183 - USERNAME [14/Nov/2017:09:33:50 +0000] "REPORT /REMOVED FOR SECURITY REASONS/default/ HTTP/1.1" 403 1421 "-" "Mac OS X/10.13.2 (17C76a) AddressBook/1808.6"
```

**Comment by skjnldsv** [comment]
Does this happens every time or only when you edit contacts?

**Comment by thoschl** [comment]
To be honest I'm not a developer and I never analyzed the protocol. But I would say the errors occur, whenever client should "receive" a change or tries to change something. In the logs I sent, you can see  PUT results in Error 412 and the REPORT ends in an 403. That seems to be an unauthorized access as far as I interpret that behavior. So something with the credentials seems to be changed.

**Comment by thoschl** [comment]
I did some research about this issue. Meanwhile I think it might be a problem with nginx. I downloaded a refrence VM from techandme.se and tested there. Everything worked.
I use nginx 1.10.3 as webserver and reverse-proxy. @CamZie how ist your configuration of nginx?

**Comment by CamZie** [comment]
@thoschl the following is the nginx config of our installation: [nginx_NC1202.txt](https://github.com/nextcloud/contacts/files/1521891/nginx_NC1202.txt) . Could you also send me yours?

**Comment by thoschl** [comment]
@CamZie of course I split my configuration in two files First is gateway (Proxy) from where I want to access the server(s) themselves (owncloud). A lot of testing tainted the config, I will clean it when the problem is solved.

[gateway.txt](https://github.com/nextcloud/contacts/files/1523309/gateway.txt)
[owncloud.txt](https://github.com/nextcloud/contacts/files/1523310/owncloud.txt)

**Comment by ppaeps** [comment]
Adding a data point: I'm also seeing this with nginx, nextcloud-12.0.4 and macOS 10.13.2.

There seems to be a strong correlation between the PUT errors in the nginx log and "invalid sync token" errors in the nextcloud logs.  Any idea on how to debug this further?

**Comment by ppaeps** [comment]
@skjnldsv:
> Does this happens every time or only when you edit contacts?

I've done a little bit more testing and it does indeed seem to be related to editing (or even deleting) contacts.

If I delete the CardDAV account and add it again, it will happily synchronise without any 412 errors as far as I can see.  Every sync seems to result in logs like this:

```
192.0.2.42 - - [05/Jan/2018:10:14:35 +0000] "PROPFIND /cloud/remote.php/dav/addressbooks/users/username/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - username [05/Jan/2018:10:14:35 +0000] "PROPFIND /cloud/remote.php/dav/addressbooks/users/username/ HTTP/1.1" 207 3511 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - username [05/Jan/2018:10:14:36 +0000] "REPORT /cloud/remote.php/dav/addressbooks/users/username/contacts/ HTTP/1.1" 403 1329 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - - [05/Jan/2018:10:35:49 +0000] "OPTIONS /cloud/remote.php/dav/principals/users/username/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - username [05/Jan/2018:10:35:50 +0000] "OPTIONS /cloud/remote.php/dav/principals/users/username/ HTTP/1.1" 200 0 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - username [05/Jan/2018:10:35:50 +0000] "PROPFIND /cloud/remote.php/dav/principals/users/username/ HTTP/1.1" 207 1569 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - - [05/Jan/2018:10:35:50 +0000] "PROPFIND /cloud/remote.php/dav/addressbooks/users/username/ HTTP/1.1" 401 569 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - username [05/Jan/2018:10:35:50 +0000] "PROPFIND /cloud/remote.php/dav/addressbooks/users/username/ HTTP/1.1" 207 3511 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
192.0.2.42 - username [05/Jan/2018:10:35:50 +0000] "REPORT /cloud/remote.php/dav/addressbooks/users/username/contacts/ HTTP/1.1" 403 1332 "-" "Mac OS X/10.13.2 (17C88) AddressBook/1808.6"
```

As soon as I edit a contact though, the 412 PUT errors as reported above start appearing.  It also looks like contacts are not synchronising correctly anymore.  At least it doesn't look like it notices contacts being deleted on another client.

This was only cursory testing.  The problem looks very easy to reproduce.

**Comment by skjnldsv** [comment]
@ppaeps can you post a screen of your network debug tab opened when editing contacts pls? Be sure to include the first contact edit request :)
Thx

**Comment by ppaeps** [comment]
@skjnldsv:
> @ppaeps can you post a screen of your network debug tab opened when editing contacts pls? Be sure to include the first contact edit request :)
Thx

I'm not sure what you mean with "network debug tab".  Do you mean tcpdump?

**Comment by hostingnuggets** [comment]
@ppaeps I think @skjnldsv means the "network" tab in your browser's web developer toolbar where you can view/debug all HTTP requests.

**Comment by ppaeps** [comment]
On 2018-01-06 07:59:33 (-0800), Hosting Nuggets wrote:
>@ppaeps I think @skjnldsv means the "network" tab in your browser's web developer toolbar where you can view/debug all HTTP requests.

I'm not doing anything in a browser though.

I'm using macOS Contacts.app.  As soon as I try to edit a contact there, I see `412 PUT` errors start to appear in my logs as reported in this thread.  I have never used the browser interface for anything related to contacts or CardDAV.

My browser can't see the HTTP traffic from Contacts.app but tcpdump obviously can.

**Comment by hostingnuggets** [comment]
Right yes this is from the MacOS contacts app of course, so we'll have to wait for @skjnldsv to answer in order to clarify what he really means with network tab.

**Comment by skjnldsv** [comment]
Ooooooh, but this changes everything! 😂
If you're not using the contacts app, this is then a server issue! :)

**Comment by ppaeps** [comment]
@skjnldsv:
>If you're not using the contacts app, this is then a server issue! :)

Yeah ... apologies if that wasn't clear.

Is this the wrong bugtracker for server issues?  Where should those be filed?  Thanks.

**Comment by skjnldsv** [comment]
No problem! 
Into https://github.com/nextcloud/server. Please search your issue before to not create duplicates! :)

**Comment by hostingnuggets** [comment]
We have the same problem with now more and people using this precise version AddressBook/1806 of the Mac OS X Contacts app with the effect that the server gets slower and slower the more people are using it. Can Nextcloud address this issue asap? It is a real problem performance and might even be used as DoS to make the whole Nextcloud unresponsive.

**Comment by skjnldsv** [comment]
@hostingnuggets same here! If you're not using the netcloud contacts application, please create an issue on the server repository. :)

**Comment by CamZie** [comment]
I have now opened the same issue on the nextcloud/server repository: https://github.com/nextcloud/server/issues/7793
