### ISSUE TITLE
NC13b3 regression: big vertical spaces in left column

### ISSUE THREAD

**Issue by nursoda** [nextcloud/contacts#453]
### Steps to reproduce
1. Upgrade to Nextcloud 13 (b3 in my case)
2. Open Contacts app
3. Group chooser / Left column is no longer neatly formatted

### Expected behaviour
Should look nicely, as it did in NC 12.
### Actual behaviour
Large vertical spaces between lines:
![grafik](https://user-images.githubusercontent.com/8425483/34159525-e202f09c-e4c9-11e7-9ca7-3398fee41021.png)

### Server configuration
**Operating system**: Debian Stretch (up to date)
**Web server:** Apache 2.4.10
**Database:** MySQL 5.5.58
**PHP version:** 5.6.30
**Nextcloud version:** 13.0.0 Beta 3
**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 12.0.4
**Where did you install Nextcloud from:** admin page / installer
**Signing status:** no errors upon signing: http://example.com/index.php/settings/integrity/failed reports "No errors have been found."
**Contacts version:** 2.0.1
**Where did you install Contacts from:** apps page / updated after NC upgrade

**List of activated apps:**: Seems irrelevant, isn't it?
**Nextcloud configuration:**
<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "seyfarth.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/seyfarth.de\/cloud",
        "dbtype": "mysql",
        "version": "13.0.0.8",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "trashbin_retention_obligation": "auto,90",
        "versions_retention_obligation": "90,auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "calendar",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "appstore.experimental.enabled": true,
        "updater.release.channel": "beta",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1
    }
}
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 57 / Chrome 63
**Operating system:** W10
**CardDAV-clients:**: issue ist with NC web interface only (browser)

#### Web server error log: No entry while doing password reset.
But I see this:
[ssl:error] AH02032: Hostname www.seyfarth.de provided via SNI and hostname seyfarth.de provided via HTTP are different
Yet, Let's Encrypt seems to be correct:
Certificate Name: seyfarth.de
  Domains: www.seyfarth.de seyfarth.de
  Expiry Date: 2018-03-07 22:32:14+00:00 (VALID: 78 days)
  Paths: ...
#### Browser log (Firefox Browser Console):
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7
getAttributeNode() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen getAttribute().  core.js:7:1714
Das nodeValue-Attribut von Attributen sollte nicht mehr verwendet werden. Verwenden Sie value stattdessen.  core.js:7:1714
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src 'nonce-NGRPZTRSdW45empjcHF3YUUwK0MwUXE3a1VrS3lWV2Fua3YrRXJOTldLUT06cTc2cTJFM2pyV3l3OVBaVFd6L3ovbWFPL25saG5SYko3VE9mS3Njdkdldz0=' 'unsafe-eval'"). Source: ondrop attribute on INPUT element.  contacts

**Comment by nursoda** [comment]
Might this (and other issues I encounter) be caused by an over-protective cross-site policy? Reason is the browser JS and the web server error log entries above, possibly caused by not honoring "Alternative DNS names" within the webserver TLS certificate?

**Comment by nursoda** [comment]
Similar issue in calendar, too: https://github.com/nextcloud/calendar/issues/666

**Comment by skjnldsv** [comment]
Thanks!
@nursoda can you try with latest nightlies? :)

**Comment by nursoda** [comment]
Sure, but how? Please step by step, like Download ZIP from github master branch, copy to server, unpack, chmod -R 640?

**Comment by skjnldsv** [comment]
Download zip from https://nightly.portknox.net/contacts/?C=M;O=D
Extract content with your http user
should be fine then

**Comment by nursoda** [comment]
No, definitely not. What I get is worse:
![grafik](https://user-images.githubusercontent.com/8425483/34181867-3f9373c2-e514-11e7-9f80-8abf4b542d1b.png)
The red dot is where my cursor is, and the bar on the left changes with the cursor position - and seems to have the right height, yet white on white ;-)

... and it seems most contact pics are not loaded or WAY slower that with 2.0.1

**Comment by onny** [comment]
For me this issue also persists with the latest Nextcloud Beta and contacts app git master

**Comment by skjnldsv** [comment]
Fixed with #438

**Comment by onny** [comment]
I tried the current git master and this issue is still present for me

**Comment by onny** [comment]
In Chromium, the stylesheet looks better but the contact list is still way too small :(
![2018-01-27-135103_swaygrab](https://user-images.githubusercontent.com/757752/35472137-b625cb48-0369-11e8-830a-7dc6a1d8ecb4.png)

**Comment by nursoda** [comment]
If you redesign the left pane, please consider sorting it, too.
As seen in last Screenshot, its unsortet, order there: F O W S U F K.

**Comment by onny** [comment]
Styling issue is still present with the latest release of contacts, version 2.1

**Comment by nursoda** [comment]
Not here: 2.1 solved it for me:
![grafik](https://user-images.githubusercontent.com/8425483/36162348-7bde8f80-10e6-11e8-9d3a-375844bfe32a.png)
However, the sorting issue remains.

**Comment by skjnldsv** [comment]
@nursoda This happens on wide screens.

**Comment by nursoda** [comment]
Hmmm, I have a screen resolution of 2440px wide and it does not happen here. In Firefox release, current. No matter how I resize the FX window.

**Comment by Henni** [comment]
@nursoda sorting is currently by amount of contacts in a group. I think we had a discussion about this before, but can't remember where.

@onny can you please make sure this isn't a caching issue?

**Comment by skjnldsv** [comment]
I can reproduce @Henni This is a server side issue, but this is created by the column system we're using here (which push the flex to the maximum)
This will require a small fix from our side and then a fix for the server :)

**Comment by onny** [comment]
@Henni: Thanks for asking. Indeed it seems to be a caching issue. It is working better now in Firefox. One thing is still present, the avatars in the contact list are not correctly vertical aliged as seen in this old screenshot here (https://github.com/nextcloud/contacts/issues/453#issuecomment-359104441). But this only affects Firefox.

**Comment by Henni** [comment]
@skjnldsv then please let us get rid of the column system.

@onny strange... the vertical misalignment flickers for me on firefox. Can you open a new issue for this?

**Comment by onny** [comment]
Yep I can do this

**Comment by nursoda** [comment]
@Henni Sorting is off-topic here, but to answer: I don't recall a discussion, wasn't aware of "sort by no of contacts in group" which I realize now. One should be able to set how to sort. For many groups/categories, this is odd.

**Comment by rollanders** [comment]
It seems almost all discussion is about the left column too wide and sorting. Most important problem is the "middle" contacts list too narrow. And details part of the window gets almost all space.

**Comment by skjnldsv** [comment]
It's being fixed in #481
