### ISSUE TITLE
Contact App does no longer handle phone numbers correctly

### ISSUE THREAD

**Issue by dautrich** [nextcloud/contacts#4572]
### Describe the bug

Yesterday, I noticed that my Nextcloud Contacts app no longer displays any phone numbers in the web interface. The phone numbers are still there, as can be seen when exporting contacts in VCF format. Adding phone numbers to an existingcontact also doesn't work; I get an error when trying to save the contact record.

My Nextcloud was updated to version 31.0.7 on July 17, 2025, and the Contacts app is on version 7.2.0.

I also noticed that the last successful synchronization with my Thunderbird was yesterday morning. Attempting to initiate a manual synchronization fails.

The dev tools of my Firefox browser shows errors:

<img width="737" height="876" alt="Image" src="https://github.com/user-attachments/assets/c6b9a19c-38d9-4d44-8e52-769e59991702" />

<img width="743" height="887" alt="Image" src="https://github.com/user-attachments/assets/2058aae2-1b50-4d39-a701-d0dc0bec2701" />

<img width="739" height="879" alt="Image" src="https://github.com/user-attachments/assets/0a1f7167-fc6e-4f4d-b61e-aa4cc1addef5" />

<img width="737" height="866" alt="Image" src="https://github.com/user-attachments/assets/afa8adfa-2c9c-4340-9c1d-3ae39825f95a" />

A contact as displayed in the Contacts app:

<img width="625" height="852" alt="Image" src="https://github.com/user-attachments/assets/533e23da-f154-4d89-9f8c-9400ef320aa9" />

The respective vCard (anonymized):
BEGIN:VCARD
VERSION:3.0
PRODID;VALUE=TEXT:-//Sabre//Sabre VObject 4.5.4//EN
UID:6e0bc7c8-c047-46c5-b957-xxxxxxxxxxxxxxxxxxxxxx
FN:Biexxxxxxx\, xxxxx
N:Biexxxxxxx;xxxxxx;;;
EMAIL;TYPE=home:xxxxxx@gmail.com
EMAIL;TYPE=work:xxxxxx@xxxxxxxxxxx.de
EMAIL:xxxxxx@xxxxxxxxxx.de
TEL;TYPE=home;VALUE=UNKNOWN:+4960xxxxxxxx
TEL;TYPE=cell;VALUE=UNKNOWN:+49 173 xxxx xxx
TEL;TYPE=work;VALUE=UNKNOWN:+49-162 xxx xxxx
ADR;TYPE=home:;;xxxxxxx;xxxxxxx;;xxxxx;
REV;VALUE=DATE-TIME:20240101T104542Z
PHOTO;ENCODING=B;TYPE=JPEG;VALUE=BINARY:/9j/4AAQSkZJRgABAQAAAQABAAD/4gIoSUN
 DX1BST0ZJTEUAAQEAAAIYAAAAAAQwAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAA
......

### Steps to reproduce

1. Go to the Nextcloud Contacts app in your browser
2. Check an entry which has at least one phone number
3. See that no phone number is displayed
4. Export the contact to VCF file
5. Check the VCF file in a text editor
6. Phone number(s) can be seen

### Expected behavior

Contact entries should be displayed, including all existing phone numbers.

### Actual behavior

No phone numbers displayed

### Contact version

7.2.0

### Operating system

Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

MySQL

**Comment by SebastianKrupinski** [comment]
Hello,

We have already addressed this issue in the following PR. https://github.com/nextcloud/contacts/pull/4569

It should be released soon.

**Comment by dautrich** [comment]
I have installed Contacts 7.2.1 in the meantime. This solves the most obvious part of this issue: With PR #4569, phone numbers are displayed again in the Contacts app.

The other problems remain:
- When I open a contact, I get an error in my browser's console log:

<img width="1372" height="872" alt="Image" src="https://github.com/user-attachments/assets/479cbea8-f101-4c51-a786-7fa2b8658879" />

- It is still not possible to add another phone number to an existing contact. (It is possible to add a new contact with a phone number).

<img width="1165" height="666" alt="Image" src="https://github.com/user-attachments/assets/fafbb969-18fa-42b1-ac23-ba99df50f230" />

- After I tried to save a contact, it's avatar image is gone.

<img width="1186" height="509" alt="Image" src="https://github.com/user-attachments/assets/f948200a-dd35-4337-aad8-0efcdf60ea5f" />


- Synchronization with Thunderbird/Cardbook doesn't work, even if you try to force it. (Last successful synchronization was at Juli 20, 2025, at 8:47 a.m.)

- I also see errors in my browser's console log when logging in:

<img width="1919" height="745" alt="Image" src="https://github.com/user-attachments/assets/560f08ff-5d2d-40d4-b9e1-135872b56c25" />

**Comment by rakekniven** [comment]
The problem described in the issue title has been fixed.

So that the developers can track and fix the other issue, I suggest that you open another issue.

btw I can confirm the behavior.

**Comment by ChristophWurst** [comment]
Assigning the triager

**Comment by SebastianKrupinski** [comment]
@dautrich your last comment is a unrelated issue. As per @rakekniven comment please open another ticket if you wish
